version: '3'
services:
  admin-server:
    container_name: admin-server
    admin-serverimage: vaiden/admin-server
  expose:
  - 9000:9000
networks:
- spring-cloud-network
discovery-server:
container_name:discovery-server
image: vaiden/discovery-serverexpose:
- 8761:8761
networks:
- spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge